Repository Kernel360/KFE3-bootup-pangpang, pull requests merged in 2025-06, with the labels that each got.

#7 Chore/dev env setup
  .eslintignore
  .eslintrc.cjs
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .vscode/settings.json
  package.json
  packages/pds_ui/tsconfig.json
  packages/pds_ui/vitest.config.ts
  packages/pds_ui/vitest.shims.d.ts
  pnpm-lock.yaml
  tsconfig.base.json
Labels: Chore

#9 Feature: TailwindCSS 디자인 토큰 적용
  packages/pds_ui/.storybook/main.ts
  packages/pds_ui/.storybook/preview.ts
  packages/pds_ui/package.json
  packages/pds_ui/postcss.config.mjs
  packages/pds_ui/src/styles/globals.css
  pnpm-lock.yaml
Labels: Feat

#12 Chore: TypeScript 설정
  .github/ISSUE_TEMPLATE/maintenance-issue.md
  .husky/pre-commit
  apps/web/src/Text.tsx
  package.json
  packages/pds_ui/src/styles/components/atom/Text.tsx
  packages/pds_ui/stories/Button.tsx
  packages/pds_ui/tsconfig.json
  pnpm-lock.yaml
  tsconfig.base.json
  tsconfig.json
Labels: Fix

#14 Feat: Text 컴포넌트 생성, 스토리북 추가
  .husky/pre-commit
  package.json
  packages/pds_ui/package.json
  packages/pds_ui/src/components/atom/Text/Text.tsx
  packages/pds_ui/src/styles/components/atom/Text.tsx
  packages/pds_ui/src/styles/globals.css
  packages/pds_ui/src/utils/cn.ts
  packages/pds_ui/stories/Text.stories.tsx
  packages/pds_ui/vitest.config.ts
  pnpm-lock.yaml
Labels: Feat

#17 Feat : Input 컴포넌트 생성 (#10)
  packages/pds_ui/package.json
  packages/pds_ui/src/components/atoms/Button/Button.stories.tsx
  packages/pds_ui/src/components/atoms/Button/Button.tsx
  packages/pds_ui/src/components/atoms/Input/Input.stories.tsx
  packages/pds_ui/src/components/atoms/Input/Input.tsx
  packages/pds_ui/src/components/atoms/Text/Text.stories.tsx
  packages/pds_ui/src/components/atoms/Text/Text.tsx
  packages/pds_ui/src/styles/components/base.css
  packages/pds_ui/src/styles/components/typography.css
  packages/pds_ui/src/styles/globals.css
  packages/pds_ui/src/styles/theme/base.css
  packages/pds_ui/src/styles/theme/borders.css
  packages/pds_ui/src/styles/theme/colors.css
  packages/pds_ui/src/styles/theme/sizing.css
  packages/pds_ui/src/styles/theme/spacing.css
  packages/pds_ui/src/styles/theme/typography.css
  packages/pds_ui/src/styles/utils/sizing-utils.css
  packages/pds_ui/src/styles/utils/spacing-utils.css
  packages/pds_ui/stories/Button.stories.ts
  packages/pds_ui/stories/Button.tsx
  packages/pds_ui/stories/Header.stories.ts
  packages/pds_ui/stories/Header.tsx
  packages/pds_ui/stories/Page.stories.ts
  packages/pds_ui/stories/Page.tsx
  packages/pds_ui/stories/button.css
  packages/pds_ui/stories/header.css
  packages/pds_ui/stories/page.css
Labels: Feat

#18 Chore: Text 컴포넌트 파일 이동
  packages/pds_ui/src/components/atom/Text/Text.stories.tsx
Labels: Refactor

#27 Refactor : Text 컴포넌트 파일 분리 및 리팩토링
  packages/pds_ui/src/components/atoms/Text/Text.tsx
  packages/pds_ui/src/components/atoms/Text/text-styles.ts
  packages/pds_ui/src/components/atoms/Text/text-types.ts
Labels: Refactor

#30 Refactor: Button Elementy Type Props Name 변경
  packages/pds_ui/src/components/atoms/Button/useButton/useButton-types.ts
  packages/pds_ui/src/components/atoms/Button/useButton/useButton.tsx
Labels: Refactor

#32 Refactor: Input 컴포넌트 리팩토링
  .eslintrc.cjs
  packages/pds_ui/src/components/atoms/Input/Input.stories.tsx
  packages/pds_ui/src/components/atoms/Input/Input.tsx
  packages/pds_ui/src/components/atoms/Input/input-styles.ts
  packages/pds_ui/src/components/atoms/Input/input-types.ts
  packages/pds_ui/src/components/atoms/Input/useInput/useInput-types.ts
  packages/pds_ui/src/components/atoms/Input/useInput/useInput.tsx
Labels: Refactor

#39 fix: Input 컴포넌트 타입 에러 수정
  packages/pds_ui/src/components/atoms/Input/Input.tsx
Labels: Bug
